name: store_management_system
description: "Store management Flutter project using Supabase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2
  google_sign_in: ^6.2.1
  flex_color_scheme: ^7.3.1
  flutter_screenutil: ^5.9.3
  fp_util: ^3.1.7
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  go_router: ^14.2.7
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700