// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVU6RYZlEYhTd5av01RYay3ZddzkiuyOk',
    appId: '1:428199118023:web:49c67c684771c6337daae2',
    messagingSenderId: '428199118023',
    projectId: 'mero-pasal-vyavasthapan',
    authDomain: 'mero-pasal-vyavasthapan.firebaseapp.com',
    storageBucket: 'mero-pasal-vyavasthapan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8VBGEmyUVdT-a6baT9qodNKGXf3aO_DM',
    appId: '1:428199118023:android:327664a845618f687daae2',
    messagingSenderId: '428199118023',
    projectId: 'mero-pasal-vyavasthapan',
    storageBucket: 'mero-pasal-vyavasthapan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1KT9kyPrQQAUSG2J0dE0GC9aqQ3wjlSw',
    appId: '1:428199118023:ios:ece13c4476832ee67daae2',
    messagingSenderId: '428199118023',
    projectId: 'mero-pasal-vyavasthapan',
    storageBucket: 'mero-pasal-vyavasthapan.appspot.com',
    iosBundleId: 'np.com.alokmishra.storeManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1KT9kyPrQQAUSG2J0dE0GC9aqQ3wjlSw',
    appId: '1:428199118023:ios:ece13c4476832ee67daae2',
    messagingSenderId: '428199118023',
    projectId: 'mero-pasal-vyavasthapan',
    storageBucket: 'mero-pasal-vyavasthapan.appspot.com',
    iosBundleId: 'np.com.alokmishra.storeManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVU6RYZlEYhTd5av01RYay3ZddzkiuyOk',
    appId: '1:428199118023:web:afcde271672511837daae2',
    messagingSenderId: '428199118023',
    projectId: 'mero-pasal-vyavasthapan',
    authDomain: 'mero-pasal-vyavasthapan.firebaseapp.com',
    storageBucket: 'mero-pasal-vyavasthapan.appspot.com',
  );
}
